FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY slang /usr/local/bin/slang
USER 65532:65532
WORKDIR /tmp
ENTRYPOINT ["/usr/local/bin/slang"]
